### ISSUE TITLE
just FYI: I also wrote "keep_as_tip"

### ISSUE THREAD

**Issue by HedvigS** [erichround/glottoTrees#1]
[I also wrote a function for making internal nodes tips and pruning tips :D!](https://github.com/HedvigS/personal-cookbook/blob/main/R/keep_nodes_and_tips.R)

Not as elegant as yours, but.. solves my immediate problem :). Just thought maybe you'd find it fun.

**Comment by HedvigS** [comment]
I checked out two solutions, and the result is almost exactly the same in my demo case. The only difference is that you don't collapse singles at the last step and I do, which I know regret. i'll sort it so I also don't collapse singles :)

Yours also does some more good checks and other smart things.

**Comment by HedvigS** [comment]
[By the way, phytools::getDescendants() has some unexpected behavior.](https://github.com/liamrevell/phytools/issues/105) It might be that I'm not understanding what's going on well enough, but so far it looks like a malfunction.

**Comment by erichround** [comment]
Thanks @HedvigS . I've worked out what the issue was and fixed it, see #3 .
