### ISSUE TITLE
keep_as_tip() checks for nodes dominating nodes, but not nodes dominating tips, within the to-be-kept set

### ISSUE THREAD

**Issue by erichround** [erichround/glottoTrees#3]
Consequently, it'll delete a node and then tell you your tree doesn't contain the tip.

Instead, it should return an error message telling you what the real problem is.

**Comment by erichround** [comment]
I've enhanced the error messaging in keep_as_tip(), which fixes the problem.

**Comment by HedvigS** [comment]
Nice one!
